function [Etaup_old,Etadown_old]=EvalDisplacement(etaup_old,etadown_old,FEM,X,nqnx)

ne=size(X,2)/nqnx;
Etaup_old=zeros(size(X))';
Etadown_old=zeros(size(X))';
for i=1:ne
    for q=1:nqnx
        Etaup_old((i-1)*nqnx + q) = Etaup_old((i-1)*nqnx + q)      ...
            + ( etaup_old( 1 +(i-1)*2)*FEM(q,1)     ...
            +   etaup_old( 2 +(i-1)*2)*FEM(q,2)     ...
            +   etaup_old( 3 +(i-1)*2)*FEM(q,3) );
         Etadown_old((i-1)*nqnx + q) = Etadown_old((i-1)*nqnx + q)      ...
            + ( etadown_old( 1 +(i-1)*2)*FEM(q,1)     ...
            +   etadown_old( 2 +(i-1)*2)*FEM(q,2)     ...
            +   etadown_old( 3 +(i-1)*2)*FEM(q,3) );
    end
end
