function [p,e,t,solNumVect,stiffMat,massMat] = my_FFimportfilemesh(fileToRead1,fileToRead2,fileToRead3,fileToRead4)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 28-Feb-2010 18:59:00

% Import the mesh file

rawData1 = importdata(fileToRead1);

np=rawData1(1,1);
p = rawData1(2:np+1,1:2)';

nt=rawData1(1,2);
t= [rawData1(np+2:2:np+1+2*nt,:)'; rawData1(np+3:2:np+2+2*nt,1)'];%; ones(1,nt)];

ne = rawData1(1,3);
e = [rawData1(np+2+2*nt:np+1+2*nt+ne,1:2)'; zeros(1,ne); ones(1,ne); ...
    rawData1(np+2+2*nt:np+1+2*nt+ne,3)'; ones(1,ne); zeros(1,ne)];

% Import the solution file

rawData2 = importdata(fileToRead2);

solStrVect = rawData2.textdata(6:(end-1));
temp = strjoin(solStrVect);
solNumVect = str2num(temp);

% Import the stiffness matrix

rawData3 = importdata(fileToRead3);

rows    = rawData3.data(2:end,1);
columns = rawData3.data(2:end,2);
values  = rawData3.data(2:end,3);

stiffMat = sparse(rows,columns,values);

% Import the mass matrix

rawData4 = importdata(fileToRead4);

rows    = rawData4.data(2:end,1);
columns = rawData4.data(2:end,2);
values  = rawData4.data(2:end,3);

massMat = sparse(rows,columns,values);

end


