function [structMesh,solNumVect,stiffMat,massMat] = my_FFimportfilemesh_3D(fileToRead1,fileToRead2,fileToRead3,fileToRead4)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 28-Feb-2010 18:59:00

% Import the mesh file

fileID = fopen(fileToRead1);
aux = textscan(fileID,'%s','Delimiter','\n');
dataStruct = aux{1};
fclose(fileID);

structMesh = [];

numbp = 6;
aux = dataStruct{numbp};
np = str2double(aux);

numbe = np + numbp + 3;
aux = dataStruct{numbe};
ne = str2double(aux);

structMesh.NumbNodes = np;
structMesh.NumbElements = ne;

p = zeros(np,3);
for ii = 1:np
    AUX = dataStruct{numbp + ii};
    C = strsplit(AUX,' ');
    
    p(ii,1) = str2double(C{1});
    p(ii,2) = str2double(C{2});
    p(ii,3) = str2double(C{3});
    
end

structMesh.Points = p;

e = zeros(ne,4);
for ii = 1:ne
    AUX = dataStruct{numbe + ii};
    C = strsplit(AUX,' ');
    
    e(ii,1) = str2double(C{1});
    e(ii,2) = str2double(C{2});
    e(ii,3) = str2double(C{3});
    e(ii,4) = str2double(C{4}); 
end

structMesh.Elements = e;
structMesh.ElementOrder = 4;

% Import the solution file

rawData2 = importdata(fileToRead2);

solStrVect = rawData2.textdata(6:(end-1));
temp = strjoin(solStrVect);
solNumVect = str2num(temp);

% Import the stiffness matrix

rawData3 = importdata(fileToRead3);

rows    = rawData3.data(2:end,1);
columns = rawData3.data(2:end,2);
values  = rawData3.data(2:end,3);

stiffMat = sparse(rows,columns,values);

% Import the mass matrix

rawData4 = importdata(fileToRead4);

rows    = rawData4.data(2:end,1);
columns = rawData4.data(2:end,2);
values  = rawData4.data(2:end,3);

massMat = sparse(rows,columns,values);

end


