Freefem_to_matlab

A tool to import Freefem meshes into matlab.

The function [p e t]=importfilemesh(<name>) reads <name> and creates the corresponding matlab-pde formatted mesh (p, e, t) that can be handeled with the matlab pde toolbox.
The function u=importfiledata(<name>) reads <name> and creates the corresponding matlab node data (u) that can be handeled with the matlab pde toolbox.

The file "freefem_example.edp" generates two files :
- A freefem-formatted mesh : "Gilgamesh.mesh"
- A node data file : "Heat.bb"
The example file shows how to read the mesh and node data generated by "freefem_example.edp", and how to plot them.

Enjoy !


Julien Dambrine.
